// templates/react/web/src/App.tsx
import { useState, type FormEvent } from "react";
import { bindings, useConnected } from "zig-webui/react";

// Bindings registered with `window.bind` in src/main.zig.
const zig = bindings<{ greet: [name: string] }>();

export function App() {
  const connected = useConnected();
  const [name, setName] = useState("React");
  const [reply, setReply] = useState("");

  async function greet(event: FormEvent) {
    event.preventDefault();
    setReply(await zig.greet(name));
  }

  return (
    <main>
      <h1>zig-webui + React</h1>
      <p className="status">{connected ? "Connected to Zig" : "Connecting…"}</p>
      <form onSubmit={greet}>
        <input value={name} onChange={(event) => setName(event.target.value)} />
        <button disabled={!connected}>Greet</button>
      </form>
      <output>{reply}</output>
    </main>
  );
}

// templates/vue/web/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { bindings, useConnected } from "zig-webui/vue";

// Bindings registered with `window.bind` in src/main.zig.
const zig = bindings<{ greet: [name: string] }>();
const connected = useConnected();
const name = ref("Vue");
const reply = ref("");

async function greet() {
  reply.value = await zig.greet(name.value);
}
</script>

<template>
  <main>
    <h1>zig-webui + Vue</h1>
    <p class="status">{{ connected ? "Connected to Zig" : "Connecting…" }}</p>
    <form @submit.prevent="greet">
      <input v-model="name" />
      <button :disabled="!connected">Greet</button>
    </form>
    <output>{{ reply }}</output>
  </main>
</template>
